"""RealiSimHQ AC Physics Tool — Production Web App"""
import os, json, io, zipfile, re
from flask import Flask, request, render_template_string, send_file, jsonify
from car_database import CAR_DATABASE, get_cars_by_make, get_car
from parts_database import (
    COILOVERS, ANGLE_KITS, WHEEL_SETUPS, BRAKE_KITS, DIFF_TYPES, TIRE_COMPOUNDS,
    get_compatible_parts,
)
from physics_engine import generate_physics

app = Flask(__name__)

# ── API Routes ────────────────────────────────────────────────────

@app.route('/api/cars')
def api_cars():
    return jsonify(get_cars_by_make())

@app.route('/api/car/<car_id>')
def api_car(car_id):
    car = get_car(car_id)
    if not car:
        return jsonify({"error": "Not found"}), 404
    return jsonify(car)

@app.route('/api/parts/<car_id>')
def api_parts(car_id):
    """Get all compatible parts for a given car."""
    return jsonify({
        "coilovers": COILOVERS,
        "angle_kits": get_compatible_parts(car_id, ANGLE_KITS),
        "wheels": WHEEL_SETUPS,
        "brakes": get_compatible_parts(car_id, BRAKE_KITS),
        "diffs": DIFF_TYPES,
        "tire_compounds": TIRE_COMPOUNDS,
    })

@app.route('/api/generate', methods=['POST'])
def api_generate():
    data = request.get_json()
    car_id = data.get("car_id")
    parts = data.get("parts", {})
    result = generate_physics(car_id, parts)
    if "error" in result:
        return jsonify(result), 400
    return jsonify(result)

@app.route('/api/download', methods=['POST'])
def api_download():
    data = request.get_json()
    car_id = data.get("car_id")
    parts = data.get("parts", {})
    result = generate_physics(car_id, parts)
    if "error" in result:
        return jsonify(result), 400

    car = get_car(car_id)
    car_name = f"{car['make']}_{car['model']}".replace(" ", "_").replace("/", "-")

    # Build INI file contents from changes
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        for filename, sections in result["changes"].items():
            lines = [f"; Generated by RealiSimHQ Physics Tool",
                     f"; Car: {result['summary']['car_name']}",
                     f"; Parts: {json.dumps(result['summary']['parts'])}",
                     ""]
            for section, values in sections.items():
                lines.append(f"[{section}]")
                for key, val in values.items():
                    lines.append(f"{key}={val}")
                lines.append("")
            zf.writestr(f"data/{filename}", "\n".join(lines))

        # Add a readme
        readme = f"""RealiSimHQ Physics Modifications
================================
Car: {result['summary']['car_name']} ({result['summary']['chassis']})
Engine: {result['summary']['engine']}

Selected Parts:
"""
        for k, v in result['summary']['parts'].items():
            readme += f"  {k}: {v}\n"
        readme += f"""
Physics Summary:
  Mass: {result['summary']['total_mass']} kg
  Natural Freq: {result['summary']['natural_freq_f']} / {result['summary']['natural_freq_r']} Hz
  Max Angle: {result['summary']['max_angle']}°
  Tire: {result['summary']['tire_compound']}

Instructions:
  1. Extract this zip into your AC car's folder
  2. The data/ folder files will override the car's physics
  3. For best results, merge these values into your existing data files
     rather than replacing them entirely
"""
        zf.writestr("README.txt", readme)

    zip_buf.seek(0)
    return send_file(zip_buf, mimetype='application/zip', as_attachment=True,
                     download_name=f"RealiSimHQ_{car_name}_physics.zip")


# ── Main Page ─────────────────────────────────────────────────────

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)


HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RealiSimHQ Physics Tool</title>
<style>
:root {
    --bg: #08080f;
    --bg2: #0e0e1a;
    --bg3: #151525;
    --border: #1a1a35;
    --border-hi: #00e5ff;
    --cyan: #00e5ff;
    --cyan-dim: #00e5ff44;
    --green: #00ff88;
    --red: #ff4466;
    --orange: #ffaa00;
    --text: #e0e0e8;
    --text2: #8888aa;
    --text3: #555577;
    --radius: 10px;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: var(--bg); color: var(--text); font-family: 'Inter', 'Segoe UI', system-ui, sans-serif; line-height: 1.5; }
a { color: var(--cyan); text-decoration: none; }

/* Layout */
.app { max-width: 1100px; margin: 0 auto; padding: 20px; }
header { text-align: center; padding: 30px 0 20px; border-bottom: 1px solid var(--border); margin-bottom: 30px; }
header h1 { font-size: 2.2em; letter-spacing: -1px; }
header h1 span { color: var(--cyan); }
header p { color: var(--text2); margin-top: 4px; font-size: 1.05em; }

/* Steps */
.step { display: none; animation: fadeIn 0.3s ease; }
.step.active { display: block; }
@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: none; } }

.step-header { display: flex; align-items: center; gap: 12px; margin-bottom: 20px; }
.step-num { background: var(--cyan); color: var(--bg); width: 36px; height: 36px; border-radius: 50%;
    display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 1.1em; flex-shrink: 0; }
.step-header h2 { font-size: 1.4em; }

/* Progress bar */
.progress { display: flex; gap: 6px; margin-bottom: 30px; }
.progress-dot { height: 4px; flex: 1; background: var(--border); border-radius: 2px; transition: background 0.3s; }
.progress-dot.done { background: var(--cyan); }
.progress-dot.current { background: linear-gradient(90deg, var(--cyan), var(--cyan-dim)); }

/* Car grid */
.make-section { margin-bottom: 20px; }
.make-name { color: var(--text2); font-size: 0.85em; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px; padding-left: 4px; }
.car-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 10px; }
.car-card {
    background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius);
    padding: 16px; cursor: pointer; transition: all 0.2s;
}
.car-card:hover { border-color: var(--cyan-dim); transform: translateY(-2px); box-shadow: 0 4px 20px #00e5ff10; }
.car-card.selected { border-color: var(--cyan); background: #00e5ff08; }
.car-card .car-title { font-size: 1.15em; font-weight: 700; }
.car-card .car-sub { color: var(--text2); font-size: 0.85em; margin-top: 2px; }
.car-card .car-specs { display: flex; gap: 12px; margin-top: 10px; flex-wrap: wrap; }
.car-card .spec { background: var(--bg3); padding: 3px 8px; border-radius: 4px; font-size: 0.78em; color: var(--text2); }

/* Parts selection */
.parts-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
@media (max-width: 768px) { .parts-grid { grid-template-columns: 1fr; } }
.part-group { background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius); padding: 16px; }
.part-group h3 { font-size: 1em; color: var(--cyan); margin-bottom: 10px; display: flex; align-items: center; gap: 8px; }
.part-option {
    padding: 10px 12px; border: 1px solid var(--border); border-radius: 6px;
    margin-bottom: 6px; cursor: pointer; transition: all 0.15s; font-size: 0.9em;
}
.part-option:hover { border-color: var(--cyan-dim); }
.part-option.selected { border-color: var(--cyan); background: #00e5ff08; }
.part-option .part-name { font-weight: 600; }
.part-option .part-brand { color: var(--text2); font-size: 0.85em; }
.part-option .part-desc { color: var(--text3); font-size: 0.8em; margin-top: 2px; }
.part-option .part-spec { color: var(--orange); font-size: 0.8em; margin-top: 2px; }

/* Results */
.summary-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px; margin-bottom: 24px; }
.summary-card { background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius); padding: 14px; }
.summary-card .label { color: var(--text2); font-size: 0.8em; text-transform: uppercase; letter-spacing: 1px; }
.summary-card .value { color: var(--cyan); font-size: 1.6em; font-weight: 700; margin-top: 2px; }
.summary-card .unit { color: var(--text3); font-size: 0.7em; }

/* Comparison table */
.comp-section { margin-bottom: 20px; }
.comp-section h3 { color: var(--text2); font-size: 0.85em; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 8px; padding-left: 4px; }
table { width: 100%; border-collapse: collapse; }
th { background: var(--bg3); color: var(--text2); padding: 8px 12px; text-align: left; font-size: 0.8em;
    text-transform: uppercase; letter-spacing: 1px; }
td { padding: 8px 12px; border-bottom: 1px solid var(--border); font-size: 0.9em; }
td.stock { color: var(--text2); }
td.modified { color: var(--green); font-weight: 600; }
td.changed { color: var(--orange); font-weight: 600; }
tr:hover { background: var(--bg2); }

/* Buttons */
.btn {
    background: var(--cyan); color: var(--bg); border: none; border-radius: var(--radius);
    padding: 14px 32px; font-size: 1.05em; font-weight: 700; cursor: pointer;
    transition: all 0.2s; display: inline-flex; align-items: center; gap: 8px;
}
.btn:hover { filter: brightness(1.15); transform: translateY(-1px); }
.btn:active { transform: translateY(0); }
.btn-outline {
    background: transparent; border: 1px solid var(--border); color: var(--text);
    border-radius: var(--radius); padding: 10px 20px; font-size: 0.9em; cursor: pointer;
    transition: all 0.2s;
}
.btn-outline:hover { border-color: var(--cyan); color: var(--cyan); }
.btn-row { display: flex; gap: 10px; margin-top: 24px; justify-content: center; flex-wrap: wrap; }

/* Selected car banner */
.selected-car-banner {
    background: var(--bg2); border: 1px solid var(--cyan-dim); border-radius: var(--radius);
    padding: 14px 20px; margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between;
}
.selected-car-banner .info { }
.selected-car-banner .car-name { font-size: 1.2em; font-weight: 700; }
.selected-car-banner .car-detail { color: var(--text2); font-size: 0.85em; }

/* Search */
.search-box { width: 100%; padding: 12px 16px; background: var(--bg2); border: 1px solid var(--border);
    border-radius: var(--radius); color: var(--text); font-size: 1em; margin-bottom: 20px; outline: none; }
.search-box:focus { border-color: var(--cyan); }
.search-box::placeholder { color: var(--text3); }

/* Loading */
.spinner { display: inline-block; width: 20px; height: 20px; border: 2px solid var(--cyan-dim);
    border-top-color: var(--cyan); border-radius: 50%; animation: spin 0.8s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }

/* Footer */
footer { text-align: center; color: var(--text3); font-size: 0.8em; padding: 40px 0 20px; border-top: 1px solid var(--border); margin-top: 40px; }
</style>
</head>
<body>
<div class="app">
    <header>
        <h1>⚡ <span>RealiSimHQ</span> Physics Tool</h1>
        <p>Real parts → Real physics → Assetto Corsa</p>
    </header>

    <div class="progress" id="progress">
        <div class="progress-dot current" data-step="1"></div>
        <div class="progress-dot" data-step="2"></div>
        <div class="progress-dot" data-step="3"></div>
    </div>

    <!-- STEP 1: Select Car -->
    <div class="step active" id="step1">
        <div class="step-header">
            <div class="step-num">1</div>
            <h2>Select Your Car</h2>
        </div>
        <input type="text" class="search-box" id="carSearch" placeholder="Search by make, model, or chassis code...">
        <div id="carList"></div>
    </div>

    <!-- STEP 2: Select Parts -->
    <div class="step" id="step2">
        <div class="step-header">
            <div class="step-num">2</div>
            <h2>Choose Your Parts</h2>
        </div>
        <div class="selected-car-banner" id="carBanner"></div>
        <div class="parts-grid" id="partsGrid"></div>
        <div class="btn-row">
            <button class="btn-outline" onclick="goStep(1)">← Back</button>
            <button class="btn" onclick="generatePhysics()">⚡ Generate Physics</button>
        </div>
    </div>

    <!-- STEP 3: Results -->
    <div class="step" id="step3">
        <div class="step-header">
            <div class="step-num">3</div>
            <h2>Physics Results</h2>
        </div>
        <div class="selected-car-banner" id="resultBanner"></div>
        <div class="summary-grid" id="summaryGrid"></div>
        <div id="comparisonTables"></div>
        <div class="btn-row">
            <button class="btn-outline" onclick="goStep(2)">← Modify Parts</button>
            <button class="btn" onclick="downloadZip()">📦 Download Physics Package</button>
        </div>
    </div>

    <footer>
        RealiSimHQ &copy; 2025 — Realistic sim physics, no cap.
    </footer>
</div>

<script>
let state = {
    step: 1,
    carId: null,
    carData: null,
    carsDb: {},
    partsDb: {},
    selectedParts: {},
    result: null,
};

// ── Init ──────────────────────────────────────────────────
async function init() {
    const resp = await fetch('/api/cars');
    state.carsDb = await resp.json();
    renderCarList();
}

// ── Navigation ────────────────────────────────────────────
function goStep(n) {
    state.step = n;
    document.querySelectorAll('.step').forEach(s => s.classList.remove('active'));
    document.getElementById('step' + n).classList.add('active');
    document.querySelectorAll('.progress-dot').forEach(d => {
        const ds = parseInt(d.dataset.step);
        d.className = 'progress-dot' + (ds < n ? ' done' : ds === n ? ' current' : '');
    });
    window.scrollTo({top: 0, behavior: 'smooth'});
}

// ── Step 1: Car Selection ─────────────────────────────────
function renderCarList(filter = '') {
    const container = document.getElementById('carList');
    container.innerHTML = '';
    const fl = filter.toLowerCase();

    for (const [make, cars] of Object.entries(state.carsDb)) {
        const filtered = cars.filter(c =>
            !fl || `${c.make} ${c.model} ${c.chassis} ${c.engine}`.toLowerCase().includes(fl)
        );
        if (!filtered.length) continue;

        const section = document.createElement('div');
        section.className = 'make-section';
        section.innerHTML = `<div class="make-name">${make}</div>`;

        const grid = document.createElement('div');
        grid.className = 'car-grid';

        for (const car of filtered) {
            const card = document.createElement('div');
            card.className = 'car-card' + (state.carId === car.id ? ' selected' : '');
            card.innerHTML = `
                <div class="car-title">${car.model}</div>
                <div class="car-sub">${car.chassis} · ${car.year}</div>
                <div class="car-specs">
                    <span class="spec">${car.engine}</span>
                    <span class="spec">${car.power_hp} HP</span>
                    <span class="spec">${car.mass_kg} kg</span>
                    <span class="spec">${car.drivetrain}</span>
                </div>
            `;
            card.onclick = () => selectCar(car.id, car);
            grid.appendChild(card);
        }
        section.appendChild(grid);
        container.appendChild(section);
    }
}

document.getElementById('carSearch').addEventListener('input', e => renderCarList(e.target.value));

async function selectCar(carId, carData) {
    state.carId = carId;
    state.carData = carData;
    state.selectedParts = {
        coilovers: 'stock', angle_kit: 'stock', wheels_f: 'stock',
        wheels_r: 'stock', brakes: 'stock', diff: 'stock', tire_compound: 'street'
    };

    // Fetch compatible parts
    const resp = await fetch(`/api/parts/${carId}`);
    state.partsDb = await resp.json();

    renderCarList(); // Update selection highlight
    renderParts();
    goStep(2);
}

// ── Step 2: Parts Selection ───────────────────────────────
function renderParts() {
    const car = state.carData;
    document.getElementById('carBanner').innerHTML = `
        <div class="info">
            <div class="car-name">${car.make} ${car.model}</div>
            <div class="car-detail">${car.chassis} · ${car.year} · ${car.engine} · ${car.power_hp} HP · ${car.mass_kg} kg</div>
        </div>
    `;

    const grid = document.getElementById('partsGrid');
    grid.innerHTML = '';

    const groups = [
        { key: 'coilovers', title: '🔧 Coilovers', data: state.partsDb.coilovers, partKey: 'coilovers', specFn: c => c.spring_rate_f_nm ? `${Math.round(c.spring_rate_f_nm/9810)}/${Math.round(c.spring_rate_r_nm/9810)} kg/mm` : 'Stock rates' },
        { key: 'angle_kits', title: '🔄 Angle Kit', data: state.partsDb.angle_kits, partKey: 'angle_kit', specFn: c => c.max_angle_deg > 0 ? `${c.max_angle_deg}° max angle` : 'Stock angle' },
        { key: 'wheels_f', title: '🛞 Wheels (F & R)', data: state.partsDb.wheels, partKey: 'wheels_f', specFn: c => c.rim_dia ? `${c.rim_dia}×${c.rim_width} ET${c.offset_mm}` : 'Stock' },
        { key: 'brakes', title: '🛑 Brake Kit', data: state.partsDb.brakes, partKey: 'brakes', specFn: c => c.torque_mult ? `+${Math.round((c.torque_mult-1)*100)}% torque` : 'Stock' },
        { key: 'diffs', title: '⚙️ Differential', data: state.partsDb.diffs, partKey: 'diff', specFn: c => c.diff_power !== undefined ? `${Math.round(c.diff_power*100)}% lock` : 'Stock' },
        { key: 'tire_compounds', title: '🏁 Tire Compound', data: state.partsDb.tire_compounds, partKey: 'tire_compound', specFn: c => `Grip: ${c.grip_mult.toFixed(2)}` },
    ];

    for (const group of groups) {
        const div = document.createElement('div');
        div.className = 'part-group';
        div.innerHTML = `<h3>${group.title}</h3>`;

        for (const [id, part] of Object.entries(group.data)) {
            const opt = document.createElement('div');
            const selected = state.selectedParts[group.partKey] === id;
            opt.className = 'part-option' + (selected ? ' selected' : '');
            opt.innerHTML = `
                <div class="part-name">${part.name}</div>
                <div class="part-brand">${part.brand || ''}</div>
                <div class="part-desc">${part.description || ''}</div>
                <div class="part-spec">${group.specFn(part)}</div>
            `;
            opt.onclick = () => {
                state.selectedParts[group.partKey] = id;
                // Sync front/rear wheels
                if (group.partKey === 'wheels_f') state.selectedParts.wheels_r = id;
                renderParts();
            };
            div.appendChild(opt);
        }
        grid.appendChild(div);
    }
}

// ── Step 3: Generate & Show Results ───────────────────────
async function generatePhysics() {
    const resp = await fetch('/api/generate', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ car_id: state.carId, parts: state.selectedParts }),
    });
    state.result = await resp.json();
    renderResults();
    goStep(3);
}

function renderResults() {
    const r = state.result;
    const s = r.summary;

    document.getElementById('resultBanner').innerHTML = `
        <div class="info">
            <div class="car-name">${s.car_name}</div>
            <div class="car-detail">${s.chassis} · ${s.year} · ${s.engine}</div>
        </div>
    `;

    // Summary cards
    const grid = document.getElementById('summaryGrid');
    grid.innerHTML = [
        ['Mass', `${s.total_mass}`, 'kg'],
        ['Sprung F', `${s.sprung_f_corner}`, 'kg/corner'],
        ['Sprung R', `${s.sprung_r_corner}`, 'kg/corner'],
        ['Nat. Freq F', `${s.natural_freq_f}`, 'Hz'],
        ['Nat. Freq R', `${s.natural_freq_r}`, 'Hz'],
        ['Max Angle', `${s.max_angle}`, '°'],
        ['Hub Mass F', `${s.hub_mass_f}`, 'kg'],
        ['Hub Mass R', `${s.hub_mass_r}`, 'kg'],
    ].map(([label, value, unit]) => `
        <div class="summary-card">
            <div class="label">${label}</div>
            <div class="value">${value} <span class="unit">${unit}</span></div>
        </div>
    `).join('');

    // Comparison tables grouped by category
    const categories = {
        suspension: 'Suspension',
        unsprung: 'Unsprung Mass',
        steering: 'Steering & Angle',
        tires: 'Tires & Wheels',
        brakes: 'Brakes',
        diff: 'Differential',
    };

    const tables = document.getElementById('comparisonTables');
    tables.innerHTML = '';

    for (const [catKey, catName] of Object.entries(categories)) {
        const items = r.comparison.filter(c => c.category === catKey);
        if (!items.length) continue;

        const section = document.createElement('div');
        section.className = 'comp-section';
        let html = `<h3>${catName}</h3><table><tr><th>Parameter</th><th>Stock</th><th>Modified</th></tr>`;
        for (const item of items) {
            const changed = item.stock !== item.modified;
            html += `<tr>
                <td>${item.param}</td>
                <td class="stock">${item.stock}</td>
                <td class="${changed ? 'changed' : 'stock'}">${item.modified}</td>
            </tr>`;
        }
        html += '</table>';
        section.innerHTML = html;
        tables.appendChild(section);
    }
}

async function downloadZip() {
    const resp = await fetch('/api/download', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ car_id: state.carId, parts: state.selectedParts }),
    });
    const blob = await resp.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RealiSimHQ_${state.carData.chassis}_physics.zip`;
    a.click();
    URL.revokeObjectURL(url);
}

// Boot
init();
</script>
</body>
</html>"""

if __name__ == '__main__':
    print("🏎️  RealiSimHQ Physics Tool")
    print("   http://localhost:5000")
    app.run(host='0.0.0.0', port=5000, debug=True)
