#!/usr/bin/env python3
"""Create an XLSX spreadsheet with AC catalog data, upload to Paddy's Drive."""
import csv
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

catalog_dir = Path('/home/paddy-bot/.openclaw/workspace/ac-physics-tool/catalog')
output = '/tmp/RealiSimHQ_AC_Content_Catalog.xlsx'

tabs = {
    'Tracks (Released)': 'tracks_released.csv',
    'Tracks (AC Folder)': 'tracks_ac_folder.csv', 
    'Cars': 'cars.csv',
    'Apps': 'apps.csv',
    'Servers': 'servers.csv',
    'Parts & Liveries': 'parts.csv',
}

# Styles
header_font = Font(bold=True, color='FFFFFF', size=11)
header_fill = PatternFill(start_color='333333', end_color='333333', fill_type='solid')
alt_fill = PatternFill(start_color='F5F5F5', end_color='F5F5F5', fill_type='solid')
thin_border = Border(
    bottom=Side(style='thin', color='DDDDDD'),
)

wb = Workbook()
# Remove default sheet
wb.remove(wb.active)

total_items = 0

for tab_name, csv_file in tabs.items():
    csv_path = catalog_dir / csv_file
    if not csv_path.exists() or csv_path.stat().st_size < 10:
        continue
    
    ws = wb.create_sheet(title=tab_name)
    
    # Read CSV
    rows = []
    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            rows.append(row)
    
    if not rows:
        continue
    
    # Write data
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = ws.cell(row=r_idx+1, column=c_idx+1, value=val)
            
            # Try to convert Size column to float
            if r_idx > 0 and c_idx == 4:  # Size (MB) column
                try:
                    cell.value = float(val)
                    cell.number_format = '#,##0.0'
                except ValueError:
                    pass
            
            # Header row styling
            if r_idx == 0:
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = Alignment(horizontal='center')
            else:
                cell.border = thin_border
                # Alternate row shading
                if r_idx % 2 == 0:
                    cell.fill = alt_fill
    
    # Auto-width columns
    for col_idx in range(len(rows[0])):
        col_letter = get_column_letter(col_idx + 1)
        max_len = 0
        for row in rows:
            if col_idx < len(row):
                max_len = max(max_len, len(str(row[col_idx])))
        ws.column_dimensions[col_letter].width = min(max_len + 3, 60)
    
    # Freeze header row
    ws.freeze_panes = 'A2'
    
    # Add autofilter
    ws.auto_filter.ref = f"A1:{get_column_letter(len(rows[0]))}{len(rows)}"
    
    item_count = len(rows) - 1  # minus header
    total_items += item_count
    print(f"  ✅ {tab_name}: {item_count} items")

# Add a Summary tab at the beginning
ws_summary = wb.create_sheet(title='Summary', index=0)
summary_data = [
    ['RealiSimHQ - Assetto Corsa Content Catalog', '', ''],
    ['', '', ''],
    ['Category', 'Items', 'Tab'],
]

for tab_name, csv_file in tabs.items():
    csv_path = catalog_dir / csv_file
    if csv_path.exists() and csv_path.stat().st_size > 10:
        with open(csv_path) as f:
            count = sum(1 for _ in f) - 1
        summary_data.append([tab_name, count, f'→ See "{tab_name}" tab'])

summary_data.append(['', '', ''])
summary_data.append(['TOTAL', total_items, ''])
summary_data.append(['', '', ''])
summary_data.append(['Generated by Paddy 🐘', '', ''])

for r_idx, row in enumerate(summary_data):
    for c_idx, val in enumerate(row):
        cell = ws_summary.cell(row=r_idx+1, column=c_idx+1, value=val)
        if r_idx == 0:
            cell.font = Font(bold=True, size=16)
        elif r_idx == 2:
            cell.font = header_font
            cell.fill = header_fill
        elif 'TOTAL' in str(val):
            cell.font = Font(bold=True, size=12)

ws_summary.column_dimensions['A'].width = 30
ws_summary.column_dimensions['B'].width = 10
ws_summary.column_dimensions['C'].width = 30

wb.save(output)
print(f"\n📁 Saved: {output}")
print(f"📊 Total: {total_items} items across {len(wb.sheetnames)-1} categories")
